### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by davebulaval** [GRAAL-Research/poutyne#158]
The formatting step in the build fail:

```
Run black --diff --check .
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.[8](https://github.com/GRAAL-Research/poutyne/runs/6163574497?check_suite_focus=true#step:5:8).12/x64/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "src/black/__init__.py", line 1423, in patched_main
  File "src/black/__init__.py", line 140[9](https://github.com/GRAAL-Research/poutyne/runs/6163574497?check_suite_focus=true#step:5:9), in patch_click
ImportError: cannot import name '_unicodefun' from 'click' (/opt/hostedtoolcache/Python/3.8.[12](https://github.com/GRAAL-Research/poutyne/runs/6163574497?check_suite_focus=true#step:5:12)/x64/lib/python3.8/site-packages/click/__init__.py)
Error: Process completed with exit code 1.
```

See [here](https://github.com/psf/black/issues/2634) for a fix. [Namely, bump to version 22.3.0](https://github.com/psf/black/issues/2634#issuecomment-1081284081).

**Comment by freud14** [comment]
Already done in commit https://github.com/GRAAL-Research/poutyne/commit/e9386a605f4e77d18a953b2e1f6a4a3905fb15fb
