### ISSUE TITLE
[BUG]Failed building wheel for torch

### ISSUE THREAD

**Issue by pengzhangzhi** [GRAAL-Research/poutyne#92]
Dear sir:
      I came across an error when I installed  poutyne with "pip install -U git+https://github.com/GRAAL-Research/poutyne.git@dev".
      I think the problem is in my torch.As the Error information said:  "ERROR: Failed building wheel for torch". But I have no idea in solving this.So I hope you can provide some solution to me. The overall error feedback is in below.
      Thanks!

ERROR: Command errored out with exit status 1:
   command: 'c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\彭张智computational AI\\AppData\\Local\\Temp\\pip-install-fgpcp5ez\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\彭张智computational AI\\AppData\\Local\\Temp\\pip-install-fgpcp5ez\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\彭张智computational AI\AppData\Local\Temp\pip-wheel-f_6axmet'
       cwd: C:\Users\彭张智computational AI\AppData\Local\Temp\pip-install-fgpcp5ez\torch\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\彭张智computational AI\AppData\Local\Temp\pip-install-fgpcp5ez\torch\setup.py", line 225, in <module>
      setup(name="torch", version="0.1.2.post2",
    File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\彭张智computational AI\AppData\Local\Temp\pip-install-fgpcp5ez\torch\setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\彭张智computational AI\\AppData\\Local\\Temp\\pip-install-fgpcp5ez\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\彭张智computational AI\\AppData\\Local\\Temp\\pip-install-fgpcp5ez\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\彭张智computational AI\AppData\Local\Temp\pip-install-fgpcp5ez\torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
Successfully built Poutyne
Failed to build torch
Installing collected packages: torch, Poutyne
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\彭张智computational AI\\AppData\\Local\\Temp\\pip-install-fgpcp5ez\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\彭张智computational AI\\AppData\\Local\\Temp\\pip-install-fgpcp5ez\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\彭 张智computational AI\AppData\Local\Temp\pip-record-e8il4qu8\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\Include\torch'
         cwd: C:\Users\彭张智computational AI\AppData\Local\Temp\pip-install-fgpcp5ez\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\彭张智computational AI\AppData\Local\Temp\pip-install-fgpcp5ez\torch\setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\彭张智computational AI\AppData\Local\Temp\pip-install-fgpcp5ez\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\彭张智computational AI\AppData\Local\Temp\pip-install-fgpcp5ez\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\彭张智computational AI\\AppData\\Local\\Temp\\pip-install-fgpcp5ez\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\彭张智computational AI\\AppData\\Local\\Temp\\pip-install-fgpcp5ez\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\彭张智computational AI\AppData\Local\Temp\pip-record-e8il4qu8\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\彭 张智computational ai\appdata\local\programs\python\python38-32\Include\torch' Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 20.2.3 is available.
You should consider upgrading via the 'c:\users\彭张智computational ai\appdata\local\programs\python\python38-32\python.exe -m pip install --upgrade pip' command.

**Comment by freud14** [comment]
Hi, on Windows, you need to install torch first using the instructions on the PyTorch's website: https://pytorch.org/get-started/locally/

As noted, on Windows, you can use this command to install torch:
``pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html``

Afterwards, you can install Poutyne as you tried.

Let me know it works.

**Comment by pengzhangzhi** [comment]
> Hi, on Windows, you need to install torch first using the instructions on the PyTorch's website: https://pytorch.org/get-started/locally/
> 
> As noted, on Windows, you can use this command to install torch:
> `pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html`
> 
> Afterwards, you can install Poutyne as you tried.
> 
> Let me know it works.

Sir,thank you for such a considerable response.But I have installed torch before in my win10. For your information, the version of my torch is :1.2.0.

**Comment by freud14** [comment]
Hi, can you try installing the latest version i.e. 1.6.0 ?

**Comment by pengzhangzhi** [comment]
Hey! Thanks for your quick response.Would you mind to give me the code that upgrade my torch?
I just tried to upgrade my torch with code 
"conda config --add channels soumith
conda update pytorch torchvision"
After successfully installed, the version is still '1.2.0'.
I was barely good at this stuff! Sorry to bother you!

**Comment by freud14** [comment]
If you use conda, according to the [website](https://pytorch.org/get-started/locally/):
``conda install pytorch torchvision cudatoolkit=10.2 -c pytorch``

**Comment by pengzhangzhi** [comment]
Still didn't work. I used the code you given to me. `conda install pytorch torchvision cudatoolkit=10.2 -c pytorch`
the result is as followed :
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
```

**Comment by freud14** [comment]
Can you try to uninstall your current PyTorch installation first? If this does not work, can you try to remove the channel soumith that you added? If these do not work, I would recommend you to completely remove Anaconda from your system and do a clean installation.

**Comment by freud14** [comment]
Hi,
Did you succeed? If so, can you close the issue?
Thank you.

**Comment by pengzhangzhi** [comment]
OK! It's very kind of you for such caring help! Thanks a million : )
